version: '3.9'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/docker/backend.Dockerfile
    env_file:
      - ../backend/.env.example
    ports:
      - "8000:8000"
    volumes:
      - ../database:/app/database
      - ../ai:/app/ai
  frontend:
    build:
      context: ..
      dockerfile: infra/docker/frontend.Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws/chat
    ports:
      - "5173:5173"
    depends_on:
      - backend

